# Generated by Django 3.1 on 2020-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0003_auto_20200831_2015"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="workflow_name",
        ),
        migrations.AddField(
            model_name="workflow",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="workflow",
            name="path",
            field=models.CharField(default="", max_length=200),
        ),
    ]
