# Generated by Django 3.1 on 2020-08-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0005_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="run",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
