# Generated by Django 3.1 on 2020-08-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0006_auto_20200831_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="timing",
            field=models.IntegerField(default=0),
        ),
    ]
