# Generated by Django 3.1 on 2020-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0009_auto_20200831_2250"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
