# Generated by Django 3.1 on 2020-09-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_run_elapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='timing',
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('jobs', models.IntegerField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.run')),
            ],
        ),
    ]
