# Generated by Django 3.1.1 on 2020-09-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0013_auto_20200902_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timing',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
